# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Node Disassemble!
tagline:          Hacking JS and circuits fo' fun.
url:              http://www.node-disassemble.com
paginate:         1
baseurl:          /
author:
  name:           Todd Lawton Beauchamp
  url:            https://twitter.com/toddlawton
  email:          toddbee@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/toddlawton/toddlawton.github.io
